apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-username: Z3JvdXAtMQ==
  mongo-password: TVRsdEtTYzlCcDJQaWJLMw==
  # mongo-uri: bW9uZ29kYitzcnY6Ly9ncm91cC1sOk1UbHRLU2M5QnAyUGliSzNAb2JhbWluYXRpb24uZmxxMG9qYi5tb25nb2RiLm5ldC9Ob2RlLUFQST9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1vYmFtaW5hdGlvbg==
