name: restaurant-cd

on:
  push:
    branches: [main]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend:${{github.run_id}}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./cute-cumbers_frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend:${{github.run_id}}

  update-manifests:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Update backend image tag
        run: |
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/backend:.*|image: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_id }}|" k8s/backend-depl.yaml
      - name: Update frontend image tag
        run: |
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_id }}|" k8s/frontend-depl.yaml
      - name: Commit and push
        run: |
          git config user.email "ci@github.com"
          git config user.name "github-actions"
          git add k8s/
          git commit -m "chore: update image tags"
          git push origin${{ github.ref_name }}
