# CI for restaurant takeaway website

name: restaurant-website

on:
  pull_request:
    branches:
      - main

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install dependencies
        run: |
          cd Backend
          npm install

      - name: backend lint check
        run: |
          cd Backend
          npm run lint

        continue-on-error: true

      - name: backend tests
        run: |
          cd Backend
          npm test

        continue-on-error: true

  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd cute-cumbers_frontend
          npm install

      - name: Run frontend lint
        run: |
          cd cute-cumbers_frontend
          npm run lint
        continue-on-error: true

      - name: Build frontend
        run: |
          cd cute-cumbers_frontend
          npm run build

  docker:
    runs-on: ubuntu-latest
    needs:
      - backend-ci
      - frontend-ci

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKENS}}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/restaurant-backend:${{github.run_id}}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/restaurant-frontend:${{github.run_id}}

  update-manifests:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Update backend image tag
        run: |
          sed -i "s|image: backend:1.0|image: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_id }}|" k8s/backend-depl.yaml

      - name: Update frontend image tag
        run: |
          sed -i "s|image: frontend:1.0|image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_id }}|" k8s/frontend-depl.yaml

      - name: Commit and push
        run: |
          git config user.email "ci@github.com"
          git config user.name "github-actions"
          git add k8s/backend/deployment.yaml k8s/frontend/deployment.yaml
          git commit -m "CI: Update k8s image tags"
          git push
